apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-nodeport
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Release.Name }}
  type: NodePort 

